services:
  - type: web
    name: restaurant-stripe-server
    env: node
    buildCommand: npm install
    startCommand: node server.js
    rootDir: backend-deploy
    envVars:
      - key: NODE_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false 